### ISSUE TITLE
Doesn't Brackets already do this?

### ISSUE THREAD

**Issue by mackenza** [caseyg1204/brackets-quoter#2]
it certainly does on mine... unless I am missing a specific use case.

Just curious

**Comment by caseyg1204** [comment]
It doesn't for me, which I was surprised by. I am using Release 1.1 build 1.1.0-15558 on a Mac. 

So when you highlight text then type a ' or " it wraps the highlighted text? For me it just replaces with the quote.

**Comment by mackenza** [comment]
Weird. I am on Linux and Windows and it works for me. I don't have a Mac to try on. 

Might it have something to do with the file type? . My tests were on js and php files.

**Comment by caseyg1204** [comment]
Hmmm. I tried html, css, less, coffee and js files without any extensions and it doesn't work. Are you doing it with no extensions enabled?

**Comment by mackenza** [comment]
You should probably post on the google groups mailing list and let one of the core guys comment.

**Comment by caseyg1204** [comment]
Ill do that. FYI I did a fresh install on windows and it did not wrap in quotes.

**Comment by glepretre** [comment]
I asked myself the same question because I already use this behavior in Brackets and find out that it's enabled with the `closeBraces` option https://github.com/adobe/brackets/issues/5778 which is quite strange. 

But the "toggle mode" suggested by #1 has been rejected by the Brackets team :disappointed: https://github.com/adobe/brackets/issues/7540

**Comment by caseyg1204** [comment]
I did find out over the weekend that this is true and I somehow missed the close brackets option.
